module.exports = [
    {
      name: "Bruno Almeida",
      age: "24",
      skills: ["HTML", "CSS", "Javascript", "Docker", "SQL"],
      job: "Full stack developer",
      city: "Santo André",
      email: "bruno-ralmeida@outlook.com",
      tel: "99999-9999",
    },
    {
      name: "Ana Paula",
      age: "18",
      skills: ["CSS", "Javascript", "UX/UI"],
      job: "Ux Designer",
      city: "Roça",
      email: "aninha@outlook.com",
      tel: "99999-9124",
    },
    {
        name: "Karina Sales",
        age: "20",
        skills: ["Postman", "Live", "Jasmine"],
        job: "QA Analisty",
        city: "Jardim Peri",
        email: "karina@outlook.com",
        tel: "99999-9123",
      },
      {
        name: "Vitor Leal",
        age: "21",
        skills: ["React", "CSS", "Javascript"],
        job: "Web developer",
        city: "Santo André",
        email: "vitor@outlook.com",
        tel: "99999-9122",
      },
      {
        name: "Danilo Siufi",
        age: "23",
        skills: ["SQL", "Nodejs", "Javascript", "Pl/SQL"],
        job: "IT Analisty",
        city: "Liberdade",
        email: "danilor@outlook.com",
        tel: "99999-9121",
      },
    ];